logging:
  level: 
    org:
      hibernate: 
        type: TRACE
quarkus:
  datasource:
    db-kind: postgresql
    username: subrutin
    password: subrutin
    jdbc:
      url: jdbc:postgresql://127.0.0.1:5432/lingkar
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
      bind-parameters: true
